// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath 'com.google.gms:google-services:4.4.4'
    }
}

apply from: "variables.gradle"

allprojects {
    // Redirect build directory outside of OneDrive to fix "Changes are not tracked" 
    // and "Cloud file provider is not running" errors.
    layout.buildDirectory.set(file("C:/gradle-builds/webuild/${project.name}"))

    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.layout.buildDirectory
}
