// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcfjfwxespjyzqzgampm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZmpmd3hlc3BqeXpxemdhbXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NTc1ODIsImV4cCI6MjA4ODUzMzU4Mn0.M6VGttff3Hbyh3LK5hTYlhc5bgQ7ZcaWNrWY1RIipx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});