// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipprznfyxbctzlhoyroa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcHJ6bmZ5eGJjdHpsaG95cm9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1ODE3MDYsImV4cCI6MjA3ODE1NzcwNn0.CxLVn6umTss_bl0j8YF4yIWiwdJJ9plswaUSMDB97jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});